import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Bot, Box, Brain, Circle, Code2, Copy, Eye, FolderKanban, Image, KeyRound, MessageSquare, Mic, Monitor, Pin, Plus, RefreshCcw, Search, Send, Settings, SlidersHorizontal, Sparkles, Terminal as TerminalIcon, Trash2, Wrench } from 'lucide-react'
import { io } from 'socket.io-client'
import { Terminal } from 'xterm'
import { FitAddon } from '@xterm/addon-fit'
import 'xterm/css/xterm.css'
import './styles.css'
import { capabilities, chat, createSession, health, models, sessionMessages, sessions, skills, toolsetsApi, type ChatMessage, type SessionMessageRecord, type SessionSummary } from './api'
import { toolCatalog, toolsets } from './toolCatalog'

type View = 'chat' | 'capabilities' | 'messaging' | 'artifacts' | 'projects' | 'memory' | 'skills' | 'settings'
type IconType = React.ComponentType<{ size?: number }>
type ContextMenuItem = { destructive?: boolean; disabled?: boolean; icon?: IconType; label: string; onSelect: () => void; separatorBefore?: boolean }
type ContextMenuState = { items: ContextMenuItem[]; title?: string; x: number; y: number } | null
type UiPrefs = { accent: string; density: 'cozy' | 'compact'; fontScale: number; showRightRail: boolean; showToolMessages: boolean; simplifyCards: boolean }
type ContextActions = { copyText: (text: string, label?: string) => void; openMenu: (event: React.MouseEvent, title: string, items: ContextMenuItem[]) => void }

const defaultPrefs: UiPrefs = { accent: '#8eb7ff', density: 'cozy', fontScale: 1, showRightRail: true, showToolMessages: false, simplifyCards: true }
const nav: Array<[View, string, IconType]> = [['chat', 'New session', Plus], ['capabilities', 'Capabilities', Brain], ['messaging', 'Messaging', MessageSquare], ['artifacts', 'Artifacts', Box], ['projects', 'Projects', FolderKanban], ['memory', 'Memory', Sparkles], ['skills', 'Skills', Wrench], ['settings', 'Settings', Settings]]

function loadPrefs(): UiPrefs { try { return { ...defaultPrefs, ...JSON.parse(localStorage.getItem('hermes-webgui:prefs') || '{}') } } catch { return defaultPrefs } }
function useJsonLoader<T>(loader: () => Promise<T>, deps: React.DependencyList = []) { const [data, setData] = useState<T | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { let alive = true; setLoading(true); loader().then(value => { if (alive) { setData(value); setError(null) } }).catch(e => { if (alive) setError(e.message) }).finally(() => { if (alive) setLoading(false) }); return () => { alive = false } }, deps); return { data, error, loading } }
function asList(data: any): any[] { return data?.sessions || data?.items || data?.data || data?.skills || data?.toolsets || [] }
function shortJson(value: unknown, max = 2400) { return JSON.stringify(value, null, 2).slice(0, max) }
function sessionId(s: SessionSummary) { return String(s.id || s.session_id || '') }
function sessionTitle(s: SessionSummary) { return s.title || s.name || s.id || s.session_id || 'Untitled' }
function normalizeMessages(records: SessionMessageRecord[], showToolMessages: boolean): ChatMessage[] { return records.filter(r => showToolMessages || (r.role !== 'tool' && !(r.role === 'assistant' && !r.content && r.tool_calls))).map(r => { const role = ['system', 'user', 'assistant', 'tool'].includes(String(r.role)) ? r.role as ChatMessage['role'] : 'assistant'; let content = r.content || ''; if (!content && r.tool_calls) content = `[tool calls]\n${shortJson(r.tool_calls, 1600)}`; if (role === 'tool' && r.tool_name) content = `[${r.tool_name}]\n${content}`; return { role, content: content || '(empty)' } }) }

function ContextMenuOverlay({ menu, close }: { menu: ContextMenuState; close: () => void }) { useEffect(() => { if (!menu) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') close() }; const onPointer = () => close(); window.addEventListener('keydown', onKey); window.addEventListener('pointerdown', onPointer); window.addEventListener('resize', close); window.addEventListener('scroll', close, true); return () => { window.removeEventListener('keydown', onKey); window.removeEventListener('pointerdown', onPointer); window.removeEventListener('resize', close); window.removeEventListener('scroll', close, true) } }, [menu, close]); if (!menu) return null; const width = 240; const left = Math.min(menu.x, window.innerWidth - width - 10); const top = Math.min(menu.y, window.innerHeight - menu.items.length * 34 - 46); return <div className="contextMenu" style={{ left: Math.max(8, left), top: Math.max(8, top), width }} onContextMenu={event => event.preventDefault()} onPointerDown={event => event.stopPropagation()}>{menu.title && <div className="contextTitle">{menu.title}</div>}{menu.items.map((item, index) => { const Icon = item.icon; return <React.Fragment key={`${item.label}-${index}`}>{item.separatorBefore && <div className="contextSeparator"/>}<button className={item.destructive ? 'destructive' : ''} disabled={item.disabled} onClick={() => { if (!item.disabled) { item.onSelect(); close() } }}>{Icon && <Icon size={15}/>}<span>{item.label}</span></button></React.Fragment> })}</div> }

function Sidebar({ activeView, contextActions, onOpenSession, selectedSessionId, setActiveView, startNewSession }: { activeView: View; contextActions: ContextActions; onOpenSession: (s: SessionSummary) => void; selectedSessionId?: string; setActiveView: (v: View) => void; startNewSession: () => void }) { return <aside className="sidebar" onContextMenu={event => contextActions.openMenu(event, 'Sidebar', [{ icon: Plus, label: 'New session', onSelect: startNewSession }, { icon: Brain, label: 'Open Capabilities', onSelect: () => setActiveView('capabilities') }, { icon: Copy, label: 'Copy current view', onSelect: () => contextActions.copyText(activeView) }])}><div className="brand"><Bot size={28}/><div><b>Hermes WebGUI</b><span>desktop parity browser shell</span></div></div><div className="nav">{nav.map(([view, name, Icon]) => <button key={view} className={activeView === view ? 'active' : ''} onClick={() => view === 'chat' ? startNewSession() : setActiveView(view)} onContextMenu={event => contextActions.openMenu(event, name, [{ icon: Icon, label: `Open ${name}`, onSelect: () => view === 'chat' ? startNewSession() : setActiveView(view) }, { icon: Copy, label: 'Copy label', onSelect: () => contextActions.copyText(name) }])}><Icon size={18}/>{name}</button>)}</div><label className="search"><Search size={16}/><input placeholder="Search sessions..." onFocus={() => setActiveView('chat')} /></label><section><h3>PINNED</h3><p className="muted">Shift-click a chat to pin</p></section><SessionList contextActions={contextActions} onOpenSession={onOpenSession} selectedSessionId={selectedSessionId} /></aside> }
function SessionList({ contextActions, onOpenSession, selectedSessionId }: { contextActions: ContextActions; onOpenSession: (s: SessionSummary) => void; selectedSessionId?: string }) { const { data, error } = useJsonLoader(sessions, []); const items = asList(data) as SessionSummary[]; return <section><h3>SESSIONS {items.length || ''}</h3>{error && <p className="warn">API: {error}</p>}{items.slice(0, 18).map(s => { const id = sessionId(s); const title = sessionTitle(s); return <button className={`session ${selectedSessionId === id ? 'selected' : ''}`} key={id || title} onClick={() => onOpenSession(s)} onContextMenu={event => contextActions.openMenu(event, title, [{ icon: MessageSquare, label: 'Open conversation', onSelect: () => onOpenSession(s) }, { icon: Copy, label: 'Copy session id', onSelect: () => contextActions.copyText(id) }, { icon: Copy, label: 'Copy title', onSelect: () => contextActions.copyText(String(title)) }, { icon: Pin, label: 'Pin session placeholder', separatorBefore: true, onSelect: () => contextActions.copyText(`Pinned session: ${title}`) }])}>• {title}<span>{s.message_count ? `${s.message_count}` : ''}</span></button> })}</section> }

function ChatPane({ contextActions, messages, selectedTitle, setMessages }: { contextActions: ContextActions; messages: ChatMessage[]; selectedTitle?: string; setMessages: React.Dispatch<React.SetStateAction<ChatMessage[]>> }) { const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); async function submit() { if (!input.trim() || busy) return; const next = [...messages, { role: 'user' as const, content: input.trim() }]; setMessages(next); setInput(''); setBusy(true); try { const res = await chat(next.filter(m => m.role !== 'tool') as ChatMessage[]); setMessages([...next, res.choices?.[0]?.message || { role: 'assistant', content: JSON.stringify(res, null, 2) }]) } catch (e) { setMessages([...next, { role: 'assistant', content: `Hermes API error: ${e instanceof Error ? e.message : String(e)}` }]) } finally { setBusy(false) } } return <main className="chat" onContextMenu={event => contextActions.openMenu(event, 'Chat', [{ icon: Plus, label: 'New local draft', onSelect: () => setInput('') }, { icon: Copy, label: 'Copy transcript', onSelect: () => contextActions.copyText(messages.map(m => `${m.role}: ${m.content}`).join('\n\n')) }, { icon: Trash2, label: 'Clear local chat', destructive: true, separatorBefore: true, onSelect: () => setMessages([{ role: 'assistant', content: 'Local chat cleared.' }]) }])}><div className="hero"><h1>HERMES AGENT</h1><p>{selectedTitle ? `loaded: ${selectedTitle}` : 'one task at a time, now in a web browser'}</p></div><div className="messages">{messages.map((m, i) => <div key={i} className={`msg ${m.role}`} onContextMenu={event => contextActions.openMenu(event, `${m.role} message`, [{ icon: Copy, label: 'Copy message', onSelect: () => contextActions.copyText(m.content) }, { icon: Copy, label: 'Copy role + message', onSelect: () => contextActions.copyText(`${m.role}: ${m.content}`) }])}><b>{m.role}</b><pre>{m.content}</pre></div>)}</div><div className="composer"><button title="New local draft" onClick={() => setInput('')}><Plus size={20}/></button><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); void submit() } }} placeholder="Ask Hermes..."/><button aria-label="Send" onClick={submit} disabled={busy}><Send size={20}/></button></div></main> }

function DataPanel({ contextActions, title, loader, icon: Icon, empty = 'No records returned.', simplifyCards = true }: { contextActions: ContextActions; title: string; loader: () => Promise<Record<string, unknown>>; icon: IconType; empty?: string; simplifyCards?: boolean }) { const { data, error, loading } = useJsonLoader(loader, [title]); const rows = asList(data); return <main className="workspace"><section className="widePanel" onContextMenu={event => contextActions.openMenu(event, title, [{ icon: Copy, label: 'Copy raw API response', onSelect: () => contextActions.copyText(shortJson(data || error || {}, 20000)) }, { icon: RefreshCcw, label: 'Refresh page', onSelect: () => window.location.reload() }])}><div className="pageTitle"><Icon size={24}/><h2>{title}</h2></div>{loading && <p className="muted">Loading…</p>}{error && <p className="warn">{error}</p>}{rows.length ? <div className="recordGrid">{rows.slice(0, 60).map((row: any, idx) => <article key={row.id || row.name || idx}><b>{row.label || row.name || row.id || row.title || `Item ${idx + 1}`}</b>{simplifyCards ? <p>{row.description || row.source || row.model || `${Object.keys(row).length} fields`}</p> : <pre>{shortJson(row, 700)}</pre>}</article>)}</div> : <p className="muted">{empty}</p>}<details><summary>Raw API response</summary><pre className="raw">{shortJson(data || error || {}, 8000)}</pre></details></section></main> }
function CapabilitiesView({ contextActions, prefs }: { contextActions: ContextActions; prefs: UiPrefs }) { return <main className="workspace"><StatusPanel contextActions={contextActions} expanded/><ToolMatrix contextActions={contextActions} large simplifyCards={prefs.simplifyCards}/></main> }
function SettingsView({ contextActions, prefs, setPrefs }: { contextActions: ContextActions; prefs: UiPrefs; setPrefs: (p: UiPrefs) => void }) { const update = (patch: Partial<UiPrefs>) => setPrefs({ ...prefs, ...patch }); return <main className="workspace"><section className="widePanel prefs"><div className="pageTitle"><SlidersHorizontal size={24}/><h2>Customize WebGUI</h2></div><div className="prefsGrid"><label>Accent color<input type="color" value={prefs.accent} onChange={e => update({ accent: e.target.value })}/></label><label>Density<select value={prefs.density} onChange={e => update({ density: e.target.value as UiPrefs['density'] })}><option value="cozy">Cozy</option><option value="compact">Compact</option></select></label><label>Font scale<input type="range" min="0.85" max="1.2" step="0.05" value={prefs.fontScale} onChange={e => update({ fontScale: Number(e.target.value) })}/></label><button type="button" onClick={() => update({ showRightRail: !prefs.showRightRail })}>Show right rail <b>{prefs.showRightRail ? 'On' : 'Off'}</b></button><button type="button" onClick={() => update({ showToolMessages: !prefs.showToolMessages })}>Tool messages <b>{prefs.showToolMessages ? 'On' : 'Off'}</b></button><button type="button" onClick={() => update({ simplifyCards: !prefs.simplifyCards })}>Simplify cards <b>{prefs.simplifyCards ? 'On' : 'Off'}</b></button><button type="button" onClick={() => update(defaultPrefs)}>Reset defaults</button></div></section><DataPanel contextActions={contextActions} title="Settings / Toolsets" loader={toolsetsApi} icon={Settings} simplifyCards={prefs.simplifyCards}/></main> }
function ToolMatrix({ contextActions, large = false, simplifyCards = true }: { contextActions: ContextActions; large?: boolean; simplifyCards?: boolean }) { const [filter, setFilter] = useState(''); const filtered = useMemo(() => toolCatalog.filter(t => `${t.name} ${t.toolset} ${t.description}`.toLowerCase().includes(filter.toLowerCase())), [filter]); return <section className={`panel tools ${large ? 'large' : ''}`}><div className="panelTitle"><Wrench/> Tools <span>{toolCatalog.length}</span></div><input className="toolSearch" placeholder="Filter every Hermes tool..." value={filter} onChange={e=>setFilter(e.target.value)} /><div className="chips">{toolsets.map(t => <button key={t} onClick={() => setFilter(t)}>{t}</button>)}</div><div className="toolGrid">{filtered.map(t => <article key={t.name} onContextMenu={event => contextActions.openMenu(event, t.name, [{ icon: Copy, label: 'Copy tool name', onSelect: () => contextActions.copyText(t.name) }, { icon: Copy, label: 'Copy tool JSON', onSelect: () => contextActions.copyText(shortJson(t, 20000)) }, { icon: Search, label: `Filter ${t.toolset}`, separatorBefore: true, onSelect: () => setFilter(t.toolset) }])}><b>{t.name}</b><small>{t.toolset}</small><p>{t.description}</p>{!simplifyCards && <pre>{shortJson(t, 500)}</pre>}{t.requires && <em>{t.requires}</em>}</article>)}</div></section> }
function StatusPanel({ contextActions, expanded = false }: { contextActions: ContextActions; expanded?: boolean }) { const { data, error } = useJsonLoader(health, []); const caps = useJsonLoader(capabilities, []); return <section className={`panel status ${expanded ? 'expanded' : ''}`} onContextMenu={event => contextActions.openMenu(event, 'Gateway status', [{ icon: Copy, label: 'Copy health JSON', onSelect: () => contextActions.copyText(shortJson(data || error || {}, 20000)) }, { icon: Copy, label: 'Copy capabilities JSON', onSelect: () => contextActions.copyText(shortJson(caps.data || caps.error || {}, 20000)) }])}><div className="panelTitle"><Circle/> Gateway ready</div><div className="kv"><span>Web server</span><b>:9119</b></div><div className="kv"><span>Hermes API</span><b>{data?.hermesReachable ? 'online' : 'offline'}</b></div><div className="kv"><span>API key</span><b>{data?.apiKeyConfigured ? 'configured' : 'missing'}</b></div>{error && <p className="warn">{error}</p>}<pre>{shortJson(caps.data || data || caps.error, expanded ? 8000 : 1800)}</pre></section> }
function WebTerminal({ contextActions }: { contextActions: ContextActions }) { useEffect(() => { const terminal = new Terminal({ cursorBlink: true, theme: { background: '#070b12', foreground: '#d7e1ff' }, fontSize: 13 }); const fit = new FitAddon(); terminal.loadAddon(fit); const el = document.getElementById('terminal')!; terminal.open(el); fit.fit(); const socket = io(); terminal.onData(data => socket.emit('terminal:input', data)); socket.on('terminal:data', data => terminal.write(data)); const resize = () => { fit.fit(); socket.emit('terminal:resize', { cols: terminal.cols, rows: terminal.rows }) }; window.addEventListener('resize', resize); resize(); return () => { window.removeEventListener('resize', resize); socket.disconnect(); terminal.dispose() } }, []); return <section className="panel term" onContextMenu={event => contextActions.openMenu(event, 'Web terminal', [{ icon: Copy, label: 'Copy terminal note', onSelect: () => contextActions.copyText('Web terminal context menu') }])}><div className="panelTitle"><TerminalIcon/> Web terminal</div><div id="terminal" /></section> }
function RightRail({ contextActions, prefs }: { contextActions: ContextActions; prefs: UiPrefs }) { if (!prefs.showRightRail) return null; return <aside className="rightRail"><StatusPanel contextActions={contextActions}/><ToolMatrix contextActions={contextActions} simplifyCards={prefs.simplifyCards}/><section className="panel quick"><div className="panelTitle"><KeyRound/> Desktop parity</div><ul><li>Click sessions to load conversations</li><li>Customize density, accent, right rail, cards and tool-message visibility</li><li>Native-feeling right-click menus on sessions, messages, tools and panels</li></ul></section><WebTerminal contextActions={contextActions}/></aside> }
function ActiveView({ activeView, contextActions, messages, prefs, selectedTitle, setMessages, setPrefs }: { activeView: View; contextActions: ContextActions; messages: ChatMessage[]; prefs: UiPrefs; selectedTitle?: string; setMessages: React.Dispatch<React.SetStateAction<ChatMessage[]>>; setPrefs: (p: UiPrefs) => void }) { if (activeView === 'capabilities') return <CapabilitiesView contextActions={contextActions} prefs={prefs} />; if (activeView === 'messaging') return <DataPanel contextActions={contextActions} title="Messaging / API Sessions" loader={sessions} icon={MessageSquare} simplifyCards={prefs.simplifyCards} />; if (activeView === 'artifacts') return <DataPanel contextActions={contextActions} title="Artifacts / Models" loader={models} icon={Box} simplifyCards={prefs.simplifyCards} />; if (activeView === 'projects') return <DataPanel contextActions={contextActions} title="Projects / Sessions" loader={sessions} icon={FolderKanban} simplifyCards={prefs.simplifyCards} />; if (activeView === 'memory') return <DataPanel contextActions={contextActions} title="Memory / Capabilities" loader={capabilities} icon={Sparkles} simplifyCards={prefs.simplifyCards} />; if (activeView === 'skills') return <DataPanel contextActions={contextActions} title="Skills" loader={skills} icon={Wrench} simplifyCards={prefs.simplifyCards} />; if (activeView === 'settings') return <SettingsView contextActions={contextActions} prefs={prefs} setPrefs={setPrefs} />; return <ChatPane contextActions={contextActions} messages={messages} selectedTitle={selectedTitle} setMessages={setMessages} /> }

function App() { const [activeView, setActiveView] = useState<View>('chat'); const [menu, setMenu] = useState<ContextMenuState>(null); const [prefs, setPrefsState] = useState<UiPrefs>(loadPrefs); const [selectedSession, setSelectedSession] = useState<SessionSummary | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([{ role: 'assistant', content: 'Hermes WebGUI is ready. Click a session in the left rail to load the conversation.' }]); useEffect(() => { localStorage.setItem('hermes-webgui:prefs', JSON.stringify(prefs)); document.documentElement.style.setProperty('--accent', prefs.accent); document.documentElement.style.setProperty('--font-scale', String(prefs.fontScale)) }, [prefs]); function setPrefs(next: UiPrefs) { setPrefsState(next) } function copyText(text: string) { void navigator.clipboard?.writeText(text).catch(() => undefined) } const contextActions: ContextActions = { copyText, openMenu: (event, title, items) => { event.preventDefault(); event.stopPropagation(); setMenu({ items, title, x: event.clientX, y: event.clientY }) } }; async function openSession(s: SessionSummary) { const id = sessionId(s); if (!id) return; setActiveView('chat'); setSelectedSession(s); setMessages([{ role: 'assistant', content: `Loading conversation: ${sessionTitle(s)}…` }]); try { const res = await sessionMessages(id); const records = asList(res) as SessionMessageRecord[]; setMessages(normalizeMessages(records, prefs.showToolMessages)) } catch (e) { setMessages([{ role: 'assistant', content: `Could not load session ${id}: ${e instanceof Error ? e.message : String(e)}` }]) } } async function startNewSession() { setActiveView('chat'); setSelectedSession(null); setMessages([{ role: 'assistant', content: 'Started a fresh local chat view. Hermes API session creation is available from the backend when you send a message.' }]); createSession().catch(() => undefined) } return <div className={`app density-${prefs.density} ${prefs.showRightRail ? '' : 'noRightRail'}`}><Sidebar activeView={activeView} contextActions={contextActions} onOpenSession={openSession} selectedSessionId={selectedSession ? sessionId(selectedSession) : undefined} setActiveView={setActiveView} startNewSession={startNewSession}/><ActiveView activeView={activeView} contextActions={contextActions} messages={messages} prefs={prefs} selectedTitle={selectedSession ? sessionTitle(selectedSession) : undefined} setMessages={setMessages} setPrefs={setPrefs}/><RightRail contextActions={contextActions} prefs={prefs}/><ContextMenuOverlay menu={menu} close={() => setMenu(null)}/><footer><span><Monitor size={14}/> webgui ready</span><span><Mic size={14}/> voice hooks planned</span><span><Image size={14}/> media/artifacts planned</span><span><Code2 size={14}/> API proxy active</span></footer></div> }
createRoot(document.getElementById('root')!).render(<App />)
