export type ToolInfo = { toolset: string; name: string; description: string; requires?: string }

export const toolCatalog: ToolInfo[] = [
  { toolset: 'browser', name: 'browser_navigate', description: 'Navigate a browser page' },
  { toolset: 'browser', name: 'browser_snapshot', description: 'Inspect page accessibility tree' },
  { toolset: 'browser', name: 'browser_click', description: 'Click page elements' },
  { toolset: 'browser', name: 'browser_type', description: 'Type into page fields' },
  { toolset: 'browser', name: 'browser_scroll', description: 'Scroll pages' },
  { toolset: 'browser', name: 'browser_back', description: 'Browser history back' },
  { toolset: 'browser', name: 'browser_press', description: 'Keyboard input' },
  { toolset: 'browser', name: 'browser_get_images', description: 'List page images' },
  { toolset: 'browser', name: 'browser_vision', description: 'Visual browser screenshot QA' },
  { toolset: 'browser', name: 'browser_console', description: 'Console logs and JS evaluation' },
  { toolset: 'browser', name: 'browser_cdp', description: 'CDP browser control', requires: 'CDP configured' },
  { toolset: 'browser', name: 'browser_dialog', description: 'Handle browser dialogs', requires: 'CDP configured' },
  { toolset: 'computer_use', name: 'computer_use', description: 'Background desktop control via cua-driver', requires: 'cua-driver' },
  { toolset: 'terminal', name: 'terminal', description: 'Execute shell commands' },
  { toolset: 'terminal', name: 'process', description: 'Manage background processes' },
  { toolset: 'terminal', name: 'read_terminal', description: 'Read embedded terminal pane' },
  { toolset: 'terminal', name: 'close_terminal', description: 'Close background terminal tab' },
  { toolset: 'file', name: 'read_file', description: 'Read text files' },
  { toolset: 'file', name: 'write_file', description: 'Write files' },
  { toolset: 'file', name: 'patch', description: 'Targeted file edits' },
  { toolset: 'file', name: 'search_files', description: 'Search files and contents' },
  { toolset: 'web', name: 'web_search', description: 'Search the web', requires: 'Search provider key' },
  { toolset: 'web', name: 'web_extract', description: 'Extract web page/PDF content', requires: 'Search provider key' },
  { toolset: 'vision', name: 'vision_analyze', description: 'Analyze images' },
  { toolset: 'image_gen', name: 'image_generate', description: 'Generate or edit images', requires: 'Image backend key' },
  { toolset: 'video', name: 'video_analyze', description: 'Analyze video content' },
  { toolset: 'video_gen', name: 'video_generate', description: 'Generate video', requires: 'Video plugin/key' },
  { toolset: 'tts', name: 'text_to_speech', description: 'Convert text to speech' },
  { toolset: 'code_execution', name: 'execute_code', description: 'Run Python scripts with Hermes tools' },
  { toolset: 'delegation', name: 'delegate_task', description: 'Spawn subagents' },
  { toolset: 'clarify', name: 'clarify', description: 'Ask user a question' },
  { toolset: 'cronjob', name: 'cronjob', description: 'Manage scheduled jobs' },
  { toolset: 'memory', name: 'memory', description: 'Persistent memory' },
  { toolset: 'session_search', name: 'session_search', description: 'Search past sessions' },
  { toolset: 'skills', name: 'skills_list', description: 'List skills' },
  { toolset: 'skills', name: 'skill_view', description: 'Read skills' },
  { toolset: 'skills', name: 'skill_manage', description: 'Create/update/delete skills' },
  { toolset: 'todo', name: 'todo', description: 'Manage session task list' },
  { toolset: 'project', name: 'project_list', description: 'List desktop projects' },
  { toolset: 'project', name: 'project_create', description: 'Create desktop project' },
  { toolset: 'project', name: 'project_switch', description: 'Switch desktop project' },
  { toolset: 'homeassistant', name: 'ha_list_entities', description: 'List Home Assistant entities', requires: 'HASS_TOKEN' },
  { toolset: 'homeassistant', name: 'ha_get_state', description: 'Get Home Assistant state', requires: 'HASS_TOKEN' },
  { toolset: 'homeassistant', name: 'ha_list_services', description: 'List Home Assistant services', requires: 'HASS_TOKEN' },
  { toolset: 'homeassistant', name: 'ha_call_service', description: 'Call Home Assistant service', requires: 'HASS_TOKEN' },
  { toolset: 'discord', name: 'discord', description: 'Discord read/send/react tools', requires: 'DISCORD_BOT_TOKEN' },
  { toolset: 'discord_admin', name: 'discord_admin', description: 'Discord moderation/admin tools', requires: 'DISCORD_BOT_TOKEN + permissions' },
  { toolset: 'spotify', name: 'spotify_playback', description: 'Control Spotify playback', requires: 'Spotify OAuth' },
  { toolset: 'spotify', name: 'spotify_devices', description: 'List/transfer devices', requires: 'Spotify OAuth' },
  { toolset: 'spotify', name: 'spotify_queue', description: 'Manage queue', requires: 'Spotify OAuth' },
  { toolset: 'spotify', name: 'spotify_search', description: 'Search Spotify catalog', requires: 'Spotify OAuth' },
  { toolset: 'spotify', name: 'spotify_playlists', description: 'Manage playlists', requires: 'Spotify OAuth' },
  { toolset: 'spotify', name: 'spotify_albums', description: 'Fetch albums', requires: 'Spotify OAuth' },
  { toolset: 'spotify', name: 'spotify_library', description: 'Manage saved music', requires: 'Spotify OAuth' },
  { toolset: 'x_search', name: 'x_search', description: 'Search X/Twitter via xAI', requires: 'xAI key/OAuth' },
  { toolset: 'kanban', name: 'kanban_show', description: 'Show active kanban task' },
  { toolset: 'kanban', name: 'kanban_list', description: 'List board tasks' },
  { toolset: 'kanban', name: 'kanban_complete', description: 'Complete task' },
  { toolset: 'kanban', name: 'kanban_block', description: 'Block task' },
  { toolset: 'kanban', name: 'kanban_heartbeat', description: 'Progress heartbeat' },
  { toolset: 'kanban', name: 'kanban_comment', description: 'Task comments' },
  { toolset: 'kanban', name: 'kanban_create', description: 'Create child tasks' },
  { toolset: 'kanban', name: 'kanban_link', description: 'Link tasks' },
  { toolset: 'kanban', name: 'kanban_unblock', description: 'Unblock task' }
]

export const toolsets = Array.from(new Set(toolCatalog.map(t => t.toolset))).sort()
